// CRM-related evidence used to support the insights generated by the agents.

export interface CRMInteraction {
  id: string;
  accountId: string;
  relatedAccount: string;
  summary: string;
  date: string;
  channel: 'email' | 'call' | 'meeting' | 'note';
  outcome: string;
  source: string;
}
